import React from 'react';

const Amar = () => {
    return (
        <div>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
            <h1>Splitting 2 Second Page</h1>
        </div>

    );
};
export default Amar;